### ISSUE TITLE
Are all methods in Table I  using VGG features?

### ISSUE THREAD

**Issue by liu666666** [microsoft/2D-TAN#11]
Thanks for nice job. @penghouwen，@Sy-Zhang

In Table I, some method do not using the vgg features in their papers, hence you replace their original feature with vgg or just copy the results from their paper?

Another question: fc6 layer of VGG16?

Thank you again for your wonderful work!

**Comment by Sy-Zhang** [comment]
We just copy their results from their paper. Since MAN achieves the previous best result and they have already compare their method with the previous methods, we simply use VGG following the MAN setting. 

We use the feature provided on the dataset website. As mentioned in their [readme](https://prior.allenai.org/projects/data/charades/README.txt), fc7 of VGG16 is extraced.
